### ISSUE TITLE
acf-input-osm javascript file conflicts with ACF block. 

### ISSUE THREAD

**Issue by margarita-boomCodes** [mcguffin/acf-field-openstreetmap#100]
Hello, 

The "acf-input-osm" javascript file creates a conflict with the ACF Block: 
when I click on the boolean ACF field a second time, there is an error in the console log (dispatched event is not a function) and the block is not accessible anymore with the error "This block has encountered an error and cannot be previewed". I made a video, so that you can see the behaviour clearer: https://www.dropbox.com/s/61bnn38p22j6urg/acf-openstreetmap-field.mov?dl=0

The solution now was to at least deregister the "acf-input-osm" script on pages that I don't need the map field.

**Comment by designzwang** [comment]
Great, how did you do that ( deregister on pages that don't need the map ... )  ? Might be helpful until this is resolved. Thanks!
Also: could be addressed here - https://github.com/mcguffin/acf-openstreetmap-field/issues/93 , sounds similar.

**Comment by margarita-boomCodes** [comment]
@designzwang Here is how I deactivated the handler except of the taxonomy pages. 

```
add_action( 'admin_enqueue_scripts', 'boom_map_asset_on_demand' );

function boom_map_asset_on_demand() {
    if ( 'edit-tags.php' === $GLOBALS['pagenow'] || 'term.php' === $GLOBALS['pagenow'] ) {
       return;	
    }

    wp_deregister_script( 'acf-input-osm' );
}
```

**Comment by designzwang** [comment]
Ah, I see - thanks!

**Comment by krisre-sigmabold** [comment]
This is caused by this line: https://github.com/mcguffin/acf-openstreetmap-field/blob/c06b05e0165317ea3fe26b340a211a98b7c49ace/src/js/acf-input-osm.js#L994

In the block editor (preview mode), ACF is sending an instance of a react component, not a DOM element, so `dispatchEvent` does not exist.  When the preview changes, it triggers the react component's "componentDidAppend" method, which passes `this.state.$el` through `acf.doAction("append")`. I suspect that `$el` is (incorrectly) a react component, and this might be an ACF bug?

There's only so much minified code I can grok, though, so I'm not sure if the problem is limited to previews (where we shouldn't care). In my case, the event _listener_ never runs, so it would be fine to simply change the code in this plugin to only call `dispatchEvent` if it exists. This would prevent this plugin from "crashing" block display when encountering this event, and it's nonsensical to try and dispatch a DOM event on a react component anyway.

**Comment by mcguffin** [comment]
@margarita-boomCodes I'm having a hard time reproducing this... 
In your Video it looks like you're using ACF 6.1.7. 
Is it still broken with ACF 6.2.0?

**Comment by krisre-sigmabold** [comment]
To reproduce: create an ACF block and associate one field with it. Add the block to a post (it loads and previews). Change the block's field (from the sidebar, staying in preview mode for the block) - ACF will request a new preview and replace the DOM elements with the new preview, that's what breaks

**Comment by vtwigt** [comment]
>  Is it still broken with ACF 6.2.0?

I am seeing the same issue using ACF Pro 6.2.0 and ACF OpenStreetMap Field 1.4.3.

As a workaround until this is fixed, would it possible in some way to dynamically dequeue the script?
I.e. since it's a custom field, the field could be added to multiple different pages, meaning the script should not be dequeued on pages that have the custom field.

In other words, what would be the best way to programmatically check if the current page needs the ACF OSM admin script?

**Comment by margarita-boomCodes** [comment]
> it still broken with ACF 6.2.0?

I can also confirm, that it still doesn't work with the ACF 6.2.1.1.

**Comment by mcguffin** [comment]
@margarita-boomCodes I am still having a hard time reproducing it – even on a fresh WordPress with only the OSM plugin and ACF Pro active.
If @krisre-sigmabold 's observation is accurate, then something is firing `acf.doAction("append")` with a wrong parameter.  
The [ACF Docs](https://www.advancedcustomfields.com/resources/javascript-api/#actions-append) clearly state, that a jQuery object is passed, not a react component.

Do you have any additional plugins running, that might interfere with ACF / Block Editor?
Which one do you have in common?
(As suggested in #101 I will add an additional check for the data type in the next version, but I really want to understand why.)

**Comment by krisre-sigmabold** [comment]
Their docs say that, but IIRC their code just adds a DOM event listener with a generic name so anything can trigger it. I also wanted to understand why, but it's too painful to trace minified code, especially across promise boundaries and layers of abstraction. It wasn't worth it to me to set up a full Gutenberg dev environment just for this.

I believe this is just an accidental side-effect - as in, ACF is behaving overly-broad here and emitting an event it didn't intend to for (reasons). I didn't observe any problems just ignoring the invalid event, so I'm guessing it's triggered by a situation the ACF authors did not expect.

**Comment by margarita-boomCodes** [comment]
> @margarita-boomCodes I am still having a hard time reproducing it – even on a fresh WordPress with only the OSM plugin and ACF Pro active. 

I've deactivated all plugins and further functionality and indeed i've found out, that the bug only fires in a very specific, but very weird case. I attach here only the relevant part of the code for the block.php and the teaser.php. 

The ACF block file:
```
<?php
$args = array(
	'is_archive' => get_field( 'query_termin_archive' ),
);

$query_args = array(
	'post_type'           => 'termin',
	'post_status'         => 'publish',
	'meta_query'          => array( // if I remove this, it works
		'relation'   => 'AND',
		array(
			'key'     => 'termin_startdate',
			'value'   => date_i18n( 'Ymd', strtotime( '+1 day', time() ) ),
			'compare' => $args['is_archive'] ? '<=' : '>=',
		)
	)
);

$query = new WP_Query( $query_args );

if ( $query->have_posts() ) {
	while ( $query->have_posts() ) {
		$query->the_post();
		get_template_part( 'partials/teaser' );
	}

	wp_reset_postdata();
}
```
 
And the partials/teaser.php
```
the_title();

?>
 <div>Some HTML</div> <!-- If I remove this, it works -->
```

Unfortunately it doesn't make any sense to me, why if I disable one of those two parts that I commented in the code above, it works.
Btw I'm also using PHP 8.0.

**Comment by gakowalski** [comment]
Problem still present in ACF 6.2.0 and ACF OpenStreetMap Field 1.5.0.

**Comment by lacke** [comment]
I also have this issue. I've tested my code on:
- WordPress 6.3.1, ACF Pro 6.2.1.1 and ACF OpenStreetMap Field 1.5.0
- WordPress 6.2.2, ACF Pro 6.2.1.1 and ACF OpenStreetMap Field 1.5.0

**Comment by mcguffin** [comment]
Version 1.5.2 came with a rewritten ACF integration. 
Did this fix the issue (which I was still not able to reproduce)?

**Comment by margarita-boomCodes** [comment]
Yes! :) Thank you!
Only in the taxonomy overview page in backend, I get a php warning. See Screenshot ![taxonomy overview](https://github.com/mcguffin/acf-openstreetmap-field/assets/28343950/bab96282-fbbd-4755-a77d-60a0fd9c9faa)
