### ISSUE TITLE
Map not shown and Settings -> openstreet map disabled most of fields

### ISSUE THREAD

**Issue by zeyzone** [mcguffin/acf-field-openstreetmap#109]
All works well though the plugin updated to the latest version.

Then I changed the map zoom setting 11 to 15 and saved. After that both open street maps  of wp-admin acf field group aread and front end  not showing the map as attached image

![error1](https://github.com/mcguffin/acf-openstreetmap-field/assets/6612267/7c36c869-073d-4d20-9fba-829868eabda9)

Further when I checked the wp admin settings > OpenStreetMap   most of settings are disabled as attached image

![error2](https://github.com/mcguffin/acf-openstreetmap-field/assets/6612267/e2c1aebd-f7db-49c5-993e-3cb76925c2c1)

Please kindly review the issue.

**Comment by schischa** [comment]
Got exactly the same error here. Also its weird because I get the message that the openseamap URL couldn't be loaded in the browser console, even though it's disabled in the settings.

**Comment by odai-alali** [comment]
It seems that for some reason, JS initializer does not respect these settings. As a temporary solution, try enabling all map layers.

## Update

I wasn't able to reproduce this bug on my local setup using the same versions of `wordpres@6.4.3`, `acf@6.2.7` and `acf_osm@1.5.6` on both my published and dev site.

An error is thrown here [tile-layer-provider.js](https://github.com/mcguffin/acf-openstreetmap-field/blob/master/src/js/lib/leaflet/tile-layer-provider.js#L12) that a provider does not exist when it's disabled in the settings page, which makes sense, but I was not able to find from where this initializer is called (no experience with leaflet) and why it's trying to initialize a disabled layer.

@mcguffin I hope you can share a tip, thanks.

**Comment by margarita-boomCodes** [comment]
@mcguffin I get the same with the following error "Undefined array key "layers". Down to version 1.5.0 it works fine again. 
![layers](https://github.com/mcguffin/acf-openstreetmap-field/assets/28343950/3ae7db85-44cd-4a04-8ae8-40f47b3f8593)

**Comment by margarita-boomCodes** [comment]
> @mcguffin I get the same with the following error "Undefined array key "layers". Down to version 1.5.0 it works fine again. 

I think I found the problem: I had deactivated some "default" maps on the options page.

**Comment by AlaplayaW** [comment]
Same problem when I deactivate maps... On the other hand, if I keep all the layers activated, it works for me.

**Comment by arius28** [comment]
Hi everyone, I experienced the same issue and I think I found a solution which worked for me, hopefully for you too. To test if it works for you, open up the file in the following path of the plugin folder /acf-openstreetmap-field/include/ACFFieldOpenstreetmap/Core/LeafletProviders.php. I am using the latest plugin version so I don't know if this might benefit older versions as well. Around line 65 there is this block of code:

`$providers = array_filter( $providers, function( $el ) {`
`    return $el !== '0';`
`} );`

if you change `return $el !== '0';` to `return $el !== '0' && $el !== false;` then you can disable map providers from the settings without getting errors.

The problem (as I understand it) is that when you disable some providers in the settings of the plugin, then in the plugin code they are still present in the providers array but instead of having their associated data like url and options, they have a value of FALSE. So the disabled provider is still passed further down to leafletJS but it does not have the neccessary information to make it work so we get errors. By changing the line above the providers with FALSE values are also filtered out.
