### ISSUE TITLE
Option to alter output format via Theme Override

### ISSUE THREAD

**Issue by spa49** [mcguffin/acf-field-openstreetmap#25]
I propose the following:
it is very nice to have the map interface when locating an address.
On the frontend however, you might want to display the information without a map, f.e. as strings only. So I suggest the following output formats for the frontend

- map & address (we have that)
- map & address & coordinates
- address & coordinates
- address
- coordinates
.

**Comment by mcguffin** [comment]
Hi. Thanks for the feedback.
Honestly I think this might be the cause of more feature request like "can we have the address above the map instead of below" – "I want the coordinates in degree-minute-second". 

For specific adjustments you can always digg through the [raw data](https://nominatim.org/release-docs/develop/api/Overview/) return format.

However for easier customization, it might be a more general approach option to override the default map output using a theme file. I'll put some thoughts into theme-override, okay?

**Comment by spa49** [comment]
absolutely got your point, I think the override is the even better and more general approach, thanks for considering! for the time being, I will see what PHP and RAW can do

thanks again!

**Comment by Cyrille37** [comment]
Is that feature solved like explained in #39: use of variables/pattern in translation file?

**Comment by mcguffin** [comment]
@Cyrille37 nope, #39 is just about the address format. This is about the HTML of the entire map.

**Comment by mcguffin** [comment]
Voilá, 
theme overrides since 5e078627a43bb170ef357b9320862df27ad5170d.
