### ISSUE TITLE
Major bug when selecting marker position when using double click

### ISSUE THREAD

**Issue by colinstringer** [mcguffin/acf-field-openstreetmap#80]
Hi, first of all I want to thank you for this plugin. It's a tool that offers precisely what I need in a project I'm working on.

But I found a bug that happens whenever I choose a new address by double clicking a location on the map. 

When you double click and save the location, it appears as though everything works fine, because the address and street get an update. However, the coordinates do not get updated! 

If you want, I can replicate it in a video demonstration.

**Comment by mcguffin** [comment]
Hi Colin,
I hope you realized that map position and marker position(s) are different things...?
Anyway, I've tried to reproduce the issue. Sadly with no success, so I'd be interested in more details.

**Comment by thatwebsiteisme** [comment]
I have the same issue where double-clicking on the map produces the wrong cords for that pin location. 

The lat cords seem to be correct, however, the long cords are completely wrong. eg I double click on a location on the map and should get something like -24.1542721, 151.883321 but I get -24.1542721, -208.1167603.

However, typing into the search box, selecting a dropdown, and then dragging the icon to the location seems to return the correct cords.

And searching for the cords returns the address value with the cords in the data so that works as well.
